### ISSUE TITLE
Install a test suite

### ISSUE THREAD

**Issue by EmCousin** [silvadaniele/covoitsite#24]
# Chore

We want to be able to test our code in an automated way, so that humans can focus on testing manually what is the most important on the website. For that, we need to code tests that ensures our code is doing what it is expected to do.

There are plenty of testing frameworks. Rails embarks Minitest by default, but I suggest you to install a very popular one instead : [Rspec](https://github.com/rspec/rspec-rails)

## Todo 
- [x] install the gem [Rspec](https://github.com/rspec/rspec-rails)
- [x] install the gem [Shoulda Matchers](https://github.com/thoughtbot/shoulda-matchers). It is an extension that enables you to write important unit tests in a single line of code
- [x] Install the gem [FactoryBot for Rails](https://github.com/thoughtbot/factory_bot_rails). It is a fixtures management rails that enables you to create data that is specific for your test environment

Just follow the instructions for each gem for now. We'll start coding tests together as soon as you are done

**Comment by silvadaniele** [comment]
C'est fini! =)
